### ISSUE TITLE
sample code

### ISSUE THREAD

**Issue by waltari2001** [guan840912/cdk-aurora-globaldatabase#115]
Hi,

I cannot get the code to deploy. Do I need to run "npm i cdk-aurora-globaldatabase' first ? Not sure where the source files should go after I create a new cdk project.

Thanks !

**Comment by guan840912** [comment]
Hi @waltari2001, yes ~ 
You need to `npm i cdk-aurora-globaldatabase` or `yarn add cdk-aurora-globaldatabase` first.

**Comment by waltari2001** [comment]
Hi,

What's the proper way to clone this repo, add to it and turn it into a CDK Lib to be imported from one's app?

Thanks!
